# Generated by Django 2.2.12 on 2020-09-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
